# Auto-generated by the Cortex Python SDK

FROM c12e/cortex-python36:7552534

WORKDIR /job

RUN conda config --add channels conda-forge

COPY conda_requirements.txt .
RUN conda install --yes --file conda_requirements.txt

RUN pip install "dill==0.2.8.2" "cortex-client==6.0.4"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY action.py .

ENTRYPOINT ["python", "action.py"]
